SCENES = {
    # ---------------- SPACE ----------------
    "day_and_night": {
        "title": "Day and Night",
        "background": "#87ceeb",
        "camera": {"pos": [0, 8, 22], "lookAt": [0, 2, 0]},
        "lights": {"ambient": 0.7, "dir": {"intensity": 0.9, "pos": [10, 18, 10]}},
        "objects": [
            {
                "type": "sphere",
                "id": "earth",
                "radius": 3.2,
                "pos": [0, 2, 0],
                "color": "#2b6cff",
            },
            {
                "type": "band",
                "id": "nightBand",
                "target": "earth",
                "color": "rgba(0,0,0,0.35)",
            },
            {
                "type": "sphere",
                "id": "sun",
                "radius": 2.2,
                "pos": [-12, 7, -8],
                "color": "#ffd34d",
                "emissive": "#ffd34d",
            },
            {
                "type": "arrow",
                "id": "sunRay",
                "from": [-9, 6, -6],
                "to": [-2.5, 3.5, -1],
                "color": "#ffd34d",
            },
            {
                "type": "label",
                "text": "Earth rotates →",
                "pos": [4.3, 5.5, 0],
                "size": 0.8,
            },
            {"type": "label", "text": "Sunlight", "pos": [-7, 6, -4], "size": 0.8},
        ],
        "animation": {
            "loop": True,
            "tracks": [
                {"target": "earth", "action": "rotateY", "speed": 0.55},
                {
                    "target": "nightBand",
                    "action": "followRotateY",
                    "targetRef": "earth",
                },
            ],
        },
    },
    "solar_system_basic": {
        "title": "Solar System (Basic Orbits)",
        "background": "#070b2a",
        "camera": {"pos": [0, 18, 30], "lookAt": [0, 0, 0]},
        "lights": {"ambient": 0.35, "dir": {"intensity": 1.1, "pos": [12, 20, 10]}},
        "objects": [
            {
                "type": "sphere",
                "id": "sun",
                "radius": 3.0,
                "pos": [0, 0, 0],
                "color": "#ffcc55",
                "emissive": "#ffcc55",
            },
            {
                "type": "orbitRing",
                "id": "ring1",
                "radius": 7.0,
                "color": "rgba(255,255,255,0.25)",
            },
            {
                "type": "orbitRing",
                "id": "ring2",
                "radius": 11.0,
                "color": "rgba(255,255,255,0.18)",
            },
            {
                "type": "sphere",
                "id": "planet1",
                "radius": 1.0,
                "pos": [7.0, 0, 0],
                "color": "#7dd3fc",
            },
            {
                "type": "sphere",
                "id": "planet2",
                "radius": 1.4,
                "pos": [11.0, 0, 0],
                "color": "#c4b5fd",
            },
            {
                "type": "label",
                "text": "Planets orbit the Sun",
                "pos": [0, 8, 0],
                "size": 0.9,
            },
        ],
        "animation": {
            "loop": True,
            "tracks": [
                {
                    "target": "planet1",
                    "action": "orbit",
                    "center": [0, 0, 0],
                    "radius": 7.0,
                    "speed": 0.9,
                    "axis": "y",
                },
                {
                    "target": "planet2",
                    "action": "orbit",
                    "center": [0, 0, 0],
                    "radius": 11.0,
                    "speed": 0.55,
                    "axis": "y",
                },
                {"target": "sun", "action": "pulse", "speed": 1.2, "amount": 0.08},
            ],
        },
    },
    # ---------------- PLANTS ----------------
    "photosynthesis": {
        "title": "Photosynthesis",
        "background": "#cfefff",
        "camera": {"pos": [0, 8, 22], "lookAt": [0, 3, 0]},
        "lights": {"ambient": 0.85, "dir": {"intensity": 0.8, "pos": [12, 20, 10]}},
        "objects": [
            {"type": "ground", "id": "ground", "y": 0, "color": "#7ccf7a"},
            {"type": "stemPlant", "id": "plant", "pos": [0, 0, 0]},
            {
                "type": "sphere",
                "id": "sun",
                "radius": 2.0,
                "pos": [-12, 12, -4],
                "color": "#ffd34d",
                "emissive": "#ffd34d",
            },
            {
                "type": "arrow",
                "id": "light",
                "from": [-10, 11, -4],
                "to": [-1.5, 5.5, 0],
                "color": "#ffd34d",
            },
            {
                "type": "arrow",
                "id": "co2",
                "from": [10, 6, 0],
                "to": [2, 5, 0],
                "color": "#64748b",
            },
            {
                "type": "arrow",
                "id": "water",
                "from": [0, 0.4, 6],
                "to": [0, 2.5, 1.5],
                "color": "#38bdf8",
            },
            {
                "type": "arrow",
                "id": "oxygen",
                "from": [0.5, 6.3, 0],
                "to": [7.5, 9, 0],
                "color": "#22c55e",
            },
            {"type": "label", "text": "Sunlight", "pos": [-8, 10, -4], "size": 0.8},
            {"type": "label", "text": "CO₂ (air)", "pos": [8.5, 6, 0], "size": 0.75},
            {
                "type": "label",
                "text": "Water (roots)",
                "pos": [-5, 1.2, 5.5],
                "size": 0.75,
            },
            {
                "type": "label",
                "text": "O₂ released",
                "pos": [7.5, 9.5, 0],
                "size": 0.75,
            },
            {
                "type": "label",
                "text": "Leaf makes food (glucose)",
                "pos": [0, 7.5, 0],
                "size": 0.85,
            },
        ],
        "animation": {
            "loop": True,
            "tracks": [
                {"target": "plant", "action": "sway", "speed": 1.2, "amount": 0.08},
                {"target": "light", "action": "flow", "speed": 1.2},
                {"target": "co2", "action": "flow", "speed": 1.0},
                {"target": "water", "action": "flow", "speed": 1.0},
                {"target": "oxygen", "action": "flow", "speed": 1.1},
                {"target": "sun", "action": "pulse", "speed": 1.0, "amount": 0.08},
            ],
        },
    },
    # ---------------- ENVIRONMENT ----------------
    "water_cycle": {
        "title": "Water Cycle",
        "background": "#bfe7ff",
        "camera": {"pos": [0, 10, 26], "lookAt": [0, 4, 0]},
        "lights": {"ambient": 0.85, "dir": {"intensity": 0.8, "pos": [12, 20, 10]}},
        "objects": [
            {"type": "ground", "id": "land", "y": 0, "color": "#79d08a"},
            {
                "type": "water",
                "id": "sea",
                "pos": [-8, 0.3, 0],
                "size": [10, 0.6, 8],
                "color": "#38bdf8",
            },
            {
                "type": "sphere",
                "id": "sun",
                "radius": 1.8,
                "pos": [12, 12, -5],
                "color": "#ffd34d",
                "emissive": "#ffd34d",
            },
            {"type": "cloud", "id": "cloud1", "pos": [-2, 10, 0]},
            {"type": "cloud", "id": "cloud2", "pos": [6, 9, -1]},
            {
                "type": "arrow",
                "id": "evap",
                "from": [-8, 1.2, 0],
                "to": [-3, 8, 0],
                "color": "#60a5fa",
            },
            {
                "type": "arrow",
                "id": "cond",
                "from": [-3, 8.5, 0],
                "to": [-2, 10, 0],
                "color": "#a7f3d0",
            },
            {
                "type": "rain",
                "id": "rain",
                "from": [6, 8.5, -1],
                "toY": 0.8,
                "color": "#2563eb",
            },
            {"type": "label", "text": "Evaporation", "pos": [-6.5, 6, 0], "size": 0.75},
            {
                "type": "label",
                "text": "Condensation",
                "pos": [-2, 11.5, 0],
                "size": 0.75,
            },
            {
                "type": "label",
                "text": "Precipitation",
                "pos": [6.5, 9.8, -1],
                "size": 0.75,
            },
        ],
        "animation": {
            "loop": True,
            "tracks": [
                {"target": "cloud1", "action": "driftX", "speed": 0.35, "amount": 2.0},
                {"target": "cloud2", "action": "driftX", "speed": 0.25, "amount": 1.6},
                {"target": "evap", "action": "flow", "speed": 1.2},
                {"target": "cond", "action": "flow", "speed": 1.0},
                {"target": "rain", "action": "rain", "speed": 1.3},
                {"target": "sun", "action": "pulse", "speed": 1.0, "amount": 0.08},
            ],
        },
    },
    # ---------------- MATTER ----------------
    "states_of_matter": {
        "title": "States of Matter: Solid, Liquid, Gas",
        "background": "#eef2ff",
        "camera": {"pos": [0, 8, 26], "lookAt": [0, 3.5, 0]},
        "lights": {"ambient": 0.9, "dir": {"intensity": 0.7, "pos": [12, 20, 10]}},
        "objects": [
            {
                "type": "label",
                "text": "Solid: packed particles",
                "pos": [-10, 7.5, 0],
                "size": 0.7,
            },
            {
                "type": "particleBox",
                "id": "solidBox",
                "pos": [-10, 3.5, 0],
                "mode": "solid",
            },
            {
                "type": "label",
                "text": "Liquid: sliding particles",
                "pos": [0, 7.5, 0],
                "size": 0.7,
            },
            {
                "type": "particleBox",
                "id": "liquidBox",
                "pos": [0, 3.5, 0],
                "mode": "liquid",
            },
            {
                "type": "label",
                "text": "Gas: fast, spread out",
                "pos": [10, 7.5, 0],
                "size": 0.7,
            },
            {"type": "particleBox", "id": "gasBox", "pos": [10, 3.5, 0], "mode": "gas"},
        ],
        "animation": {
            "loop": True,
            "tracks": [
                {"target": "liquidBox", "action": "particles", "speed": 1.0},
                {"target": "gasBox", "action": "particles", "speed": 1.5},
            ],
        },
    },
    # ---------------- PHYSICS ----------------
    "forces_motion": {
        "title": "Force and Motion",
        "background": "#e8f7ff",
        "camera": {"pos": [0, 8, 24], "lookAt": [0, 2.5, 0]},
        "lights": {"ambient": 0.85, "dir": {"intensity": 0.8, "pos": [12, 20, 10]}},
        "objects": [
            {"type": "ground", "id": "ground", "y": 0, "color": "#c7f9cc"},
            {
                "type": "box",
                "id": "crate",
                "size": [3, 3, 3],
                "pos": [-6, 1.5, 0],
                "color": "#f59e0b",
            },
            {
                "type": "arrow",
                "id": "push",
                "from": [-11, 2.6, 0],
                "to": [-7.6, 2.6, 0],
                "color": "#ef4444",
            },
            {
                "type": "label",
                "text": "Push → crate moves",
                "pos": [-6, 6.5, 0],
                "size": 0.85,
            },
        ],
        "animation": {
            "loop": True,
            "tracks": [
                {"target": "crate", "action": "moveX", "speed": 1.0, "amount": 10.0},
                {"target": "push", "action": "flow", "speed": 1.2},
            ],
        },
    },
}
